### ISSUE TITLE
Add a way to know when an app has been spanned from a particular widget

### ISSUE THREAD

**Issue by GroovinChip** [MisterJimson/multi_screen_layout#2]
It would be helpful to have a way to know if an app has been spanned from a particular widget. For example, let's say we have a list of items as the child for our `TwoPageLayout`, and a `DetailView` widget representing the contents of an item in the list. When not spanned, you'll see the list of items, and tapping on an item brings you into the `DetailView` to see the contents for that item, like so:

![Screenshot_1599158391](https://user-images.githubusercontent.com/4250470/92154209-6ecd3700-edf3-11ea-9edf-90203db0daca.png)
![Screenshot_1599158393](https://user-images.githubusercontent.com/4250470/92154218-7260be00-edf3-11ea-80a8-020fa3f188d7.png)

When spanned, you'll see the list on the left and the `DetailView` on the right, like so: 

![Screenshot_1599158384](https://user-images.githubusercontent.com/4250470/92154228-78569f00-edf3-11ea-926e-6b12760cad3f.png)

This is all fine, except when spanning from within the `DetailView`. So when not spanned, you tap on an item, and from the `DetailView` you span the app. You'd expect to see the list on the left again, right? What actually happens is that the `DetailView` will span across both screens:

![Screenshot_1599158398](https://user-images.githubusercontent.com/4250470/92154247-7f7dad00-edf3-11ea-8b83-145714d28d21.png)

It would therefore be useful to be able to tell when we have spanned from a particular widget.

**Comment by MisterJimson** [comment]
Can you do this from the `MultiScreenInfo` widget? There is a note in the readme about it.
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: MultiScreenInfo(
        builder: (info) {
          return Column(
            children: <Widget>[
              Text('isAppSpanned: ${info.isSpanned}'),
            ],
          );
        },
      ),
    );
  }
}
```

**Comment by GroovinChip** [comment]
I do actually use `MultiScreenInfo` above the `DetailView` widget, and it does say the app is spanned in the context of the final screenshot from above. While technically correct, it doesn't provide enough information about the span. I don't know if it's possible, but knowing where the span started from would be useful. Perhaps some optional identifier could be added to `TwoPageLayout` that would say "if spanned from this widget, rebuild to initial layout" or something like that?

**Comment by MisterJimson** [comment]
I think I see what you are saying. I am working on more examples and master/detail is one of the use cases I haven’t spent enough time on yet. I'll recreate and see how it goes. The use case definitely makes sense.

**Comment by GroovinChip** [comment]
Thanks! You can find my full sample of this here: https://github.com/GroovinChip/surface_duo_flutter_experiment/tree/iteration_4

**Comment by MisterJimson** [comment]
If you are interested, checkout my super rough idea of how maybe to do this.

https://github.com/MisterJimson/multi_screen_layout/tree/master-detail

I think there is definitely possibility to make this type of thing easier to do, but this does work.

**Comment by MisterJimson** [comment]
The new MasterDetailLayout & MasterDetailLayoutExample should help you achieve that easily now. On that same branch for now. Thanks your example helped a lot.

**Comment by MisterJimson** [comment]
#3

**Comment by GroovinChip** [comment]
I'll check this out on Monday, thank you!

**Comment by GroovinChip** [comment]
This works quite well, thank you!
